// Supported item codes for each form type
const formTypeItemCodes = {
    "ANNUAL": [
      "1",
      "1A",
      "1B",
      "1C",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "7A",
      "8",
      "9",
      "9A",
      "9B",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
    ],
    "QUARTERLY": [
      "part1item1",
      "part1item2",
      "part1item3",
      "part1item4",
      "part2item1",
      "part2item1a",
      "part2item2",
      "part2item3",
      "part2item4",
      "part2item5",
      "part2item6",
    ],
    "8-K": [
      "1-1",
      "1-2",
      "1-3",
      "1-4",
      "1-5",
      "2-1",
      "2-2",
      "2-3",
      "2-4",
      "2-5",
      "2-6",
      "3-1",
      "3-2",
      "3-3",
      "4-1",
      "4-2",
      "5-1",
      "5-2",
      "5-3",
      "5-4",
      "5-5",
      "5-6",
      "5-7",
      "5-8",
      "6-1",
      "6-2",
      "6-3",
      "6-4",
      "6-5",
      "6-6",
      "6-10",
      "7-1",
      "8-1",
      "9-1",
    ],
  };

  module.exports = formTypeItemCodes;  // Export the object
  